# Minecraft server properties
# AOF6 Server Configuration

# Network
server-port=25565
server-ip=
max-players=10
online-mode=true
network-compression-threshold=256

# RCON - Remote Console (for Discord bot)
enable-rcon=true
rcon.port=25575
rcon.password=CHANGE_ME_IN_RAILWAY

# World
level-name=world
level-seed=
level-type=default
gamemode=survival
difficulty=normal
hardcore=false
pvp=true

# Performance
view-distance=10
simulation-distance=10
max-tick-time=60000
sync-chunk-writes=true

# Misc
motd=AerySandbox - All of Fabric 6
enable-command-block=false
spawn-protection=16
allow-flight=true
white-list=false
enforce-whitelist=false
